### ISSUE TITLE
Long Entry level

### ISSUE THREAD

**Issue by Eris919** [deankinane/HOLO_Trade_Manager#2]
Hello, 
Did the EA place the "Long Entry @" at the correct level? Should it not be at the top line of the Green block?

![HotForex MetaTrader](https://user-images.githubusercontent.com/73355169/97026522-c701f900-1559-11eb-8ea2-72ede04581f0.png)

Thank you

**Comment by deankinane** [comment]
No, this entry is correct.
For long orders, you want to enter when the bid reaches the high of the zone, not the ask. Because if this, the spread factored in when placing the order.

Hope that helps.

**Comment by Eris919** [comment]
Thank you for your reply.
